//! Shared publish-time validation for wasm-js-bridge npm artifacts.
//!
//! Each WASM crate's `validate` feature calls into this crate rather than
//! duplicating the artifact-check + TypeScript + Flow pipeline.

use std::path::Path;
use std::process::Command;

/// ESM entry point generated by `wasm-js-bridge build-workspace`.
pub const ARTIFACT_JS: &str = "index.js";
/// CommonJS entry point generated by `wasm-js-bridge build-workspace`.
pub const ARTIFACT_CJS: &str = "index.cjs";
/// TypeScript declarations generated by the `ts` feature codegen test.
pub const ARTIFACT_DTS: &str = "index.d.ts";
/// Flow type declarations generated by the `flow` feature codegen test.
pub const ARTIFACT_FLOW: &str = "index.js.flow";

/// Check that all npm artifacts exist, then validate `index.d.ts` with the
/// TypeScript compiler and `index.js.flow` with the Flow parser.
///
/// Returns `Ok(())` when all checks pass. Returns `Err` with a human-readable
/// message on the first failure.
pub fn validate_artifacts(crate_dir: &Path) -> Result<(), String> {
    // Artifact existence
    for name in [ARTIFACT_JS, ARTIFACT_DTS, ARTIFACT_FLOW] {
        if !crate_dir.join(name).exists() {
            return Err(format!(
                "{name} missing in {} — run: wasm-js-bridge build-workspace",
                crate_dir.display()
            ));
        }
    }

    // TypeScript: type-check index.d.ts via TypeScript compiler API (QuickJS, no subprocess)
    let ts_source = std::fs::read_to_string(crate_dir.join(ARTIFACT_DTS))
        .map_err(|e| format!("failed to read {ARTIFACT_DTS}: {e}"))?;
    let ts_checker = typescript_checker::TypeScriptChecker::new()
        .map_err(|e| format!("failed to create TypeScriptChecker: {e}"))?;
    let ts_diags = ts_checker
        .diagnostics(&ts_source)
        .map_err(|e| format!("TypeScriptChecker runtime error: {e}"))?;
    if !ts_diags.is_empty() {
        let msg = ts_diags
            .iter()
            .map(|d| {
                if let Some(s) = &d.start {
                    format!("  {}:{} — {}", s.line, s.column, d.message)
                } else {
                    format!("  {}", d.message)
                }
            })
            .collect::<Vec<_>>()
            .join("\n");
        return Err(format!("TypeScript errors in {ARTIFACT_DTS}:\n{msg}"));
    }

    // Flow: parse index.js.flow via flow-parser Rust crate (QuickJS, no subprocess)
    let flow_source = std::fs::read_to_string(crate_dir.join(ARTIFACT_FLOW))
        .map_err(|e| format!("failed to read {ARTIFACT_FLOW}: {e}"))?;
    let parser = flowjs_parser::FlowParser::new()
        .map_err(|e| format!("failed to create FlowParser: {e}"))?;
    let flow_diags = parser
        .diagnostics(&flow_source)
        .map_err(|e| format!("FlowParser runtime error: {e}"))?;
    if !flow_diags.is_empty() {
        let msg = flow_diags
            .iter()
            .map(|d| {
                if let Some(loc) = &d.loc {
                    format!("  {}:{} — {}", loc.start.line, loc.start.column, d.message)
                } else {
                    format!("  {}", d.message)
                }
            })
            .collect::<Vec<_>>()
            .join("\n");
        return Err(format!("Flow parse errors in {ARTIFACT_FLOW}:\n{msg}"));
    }

    Ok(())
}

/// Run an ESM smoke test against the generated `index.js` via Node.js.
///
/// The `script` is passed to `node --input-type=module -e <script>` and
/// executed in `crate_dir` so relative imports resolve to the generated
/// artifacts in that directory.
///
/// Returns `Ok(())` on exit code 0, `Err` with combined stdout/stderr otherwise.
pub fn run_esm_smoke_test(crate_dir: &Path, script: &str) -> Result<(), String> {
    let out = Command::new("node")
        .args(["--input-type=module", "-e", script])
        .current_dir(crate_dir)
        .output()
        .map_err(|e| {
            if e.kind() == std::io::ErrorKind::NotFound {
                "node not found on PATH — install Node.js: https://nodejs.org".to_string()
            } else {
                format!("failed to spawn node: {e}")
            }
        })?;

    if out.status.success() {
        Ok(())
    } else {
        Err(format!(
            "stdout:\n{}\nstderr:\n{}",
            String::from_utf8_lossy(&out.stdout),
            String::from_utf8_lossy(&out.stderr),
        ))
    }
}
